services:
  api:
    build: .
    env_file: analysis.env
    environment:
      - MAX_UPLOAD_SIZE=100MB
    ports:
      - "8000:8000"
    volumes:
      - ./models:/srv/models
      - ./app:/srv/app
      - ./workers:/srv/workers
    depends_on: [redis]
  
  worker:
    build: .
    env_file: analysis.env
    command: celery -A workers.tasks worker -l info
    volumes:
      - ./models:/srv/models
      - ./workers:/srv/workers
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]