services:
  api:
    build: .
    env_file: analysis.env
    environment:
      - MAX_UPLOAD_SIZE=100MB
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=maple_audio_db
    ports:
      - "8000:8000"
    volumes:
      - ./models:/srv/models
      - ./app:/srv/app
      - ./workers:/srv/workers
    depends_on: [redis, mongo]
  
  worker:
    build: .
    env_file: analysis.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=maple_audio_db
    command: celery -A workers.tasks worker -l info
    volumes:
      - ./models:/srv/models
      - ./workers:/srv/workers
      - ./app:/srv/app
    depends_on: [redis, mongo]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:

networks:
  default:
    name: maple-network
    driver: bridge