version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  
  api:
    build: .
    env_file: analysis.env
    environment:
      - MAX_UPLOAD_SIZE=100MB
    expose:
      - "8000"
    volumes:
      - ./models:/srv/models
    depends_on: [redis]
  
  worker:
    build: .
    env_file: analysis.env
    command: celery -A workers.tasks worker -l info
    volumes:
      - ./models:/srv/models
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]