version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    volumes:
      - ./models:/srv/models
    depends_on: [redis]
  
  worker:
    build: .
    env_file: .env
    command: celery -A workers.tasks worker -l info
    volumes:
      - ./models:/srv/models
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]