name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pytest -v
  
  docker:
    needs: test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 직접 docker 명령을 사용하여 이미지 생성 및 푸시
      - name: Build and push image
        run: |
          # GitHub Container Registry에 로그인
          echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # 이미지 빌드
          docker build -t ghcr.io/org/analysis-service:latest .
          
          # 이미지 푸시
          docker push ghcr.io/org/analysis-service:latest